from .animals.terrestrial import IsTerrestrial
from .animals.freshwater import IsFreshwater
from interfaces.animals.aquatic import IsAquatic
from .animals.actions.flying import IsFlying
from .animals.actions.walking import IsWalking
from .animals.actions.swimming import IsSwimming
from .identifiable import Identifiable
from .habitats.contains_animals import IContainsAnimals
from .habitats.contains_plants import IContainsPlants
from .habitats.is_stagnant import IsStagnant
